### ISSUE TITLE
empty stats when specifyin -n

### ISSUE THREAD

**Issue by athoune** [xcir/python-varnishapi#18]
With CLI, I can use:
```
varnishstat -n translation -1
```
It returns lots of stuff.

I want to do the same with python :

```
import varnishapi

vsc = varnishapi.VarnishStat(opt=["-n translation"])
r = vsc.getStats()
for k, v in r.iteritems():
        print k, v
vsc.Fini()
```
Notice that opt is a list of string.

It print nothing.

When I debug, in __gestat, bool(pt) is False and pt is a varnishapi.LP_VSC_point. VSM_n_Arg return 1. Everything seems OK, but it returns nothing.

**Comment by xcir** [comment]
Hi,
Could you make this
> vsc = varnishapi.VarnishStat(opt=["-n", "translation"])

ref: https://github.com/xcir/python-varnishapi#varnishstat__init__
