### ISSUE TITLE
Issues with -c switch

### ISSUE THREAD

**Issue by ema** [xcir/python-varnishapi#65]
Hi,
there seems to be a bug in the way the -c switch is honored:
https://github.com/xcir/python-varnishapi/blob/master/src/varnishapi.py#L891

When passing -c, in case of  VSL_t_req transactions the conditional on line 891 is False (because vsl[0].c_opt is True). However, the final conditional on line 895 is True, and the transaction gets ignored.

**Comment by xcir** [comment]
Thank you for your report.
This code is unnecessary and had bug.
In Varnish had match processing(/lib/libvarnishapi/vcl.c)

Thanks!
